
local c = require('moonlight.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- highlights
  hl(0, "Normal", { fg = c.fg, bg = c.bg })
  hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
  hl(0, "NormalSB", { fg = c.fg_sidebar, bg = c.bg_sidebar })
  hl(0, "NormalFloat", { fg = c.fg_float, bg = c.bg_float })
  hl(0, "SignColumn", { fg = c.fg_gutter, bg = c.bg })
  hl(0, "SignColumnSB", { fg = c.fg_gutter, bg = c.bg_sidebar })
  hl(0, "MsgArea", { fg = c.fg_dark, bg = 'NONE' })
  hl(0, "ModeMsg", { fg = c.fg_dark, bg = 'NONE', bold=true, })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
  hl(0, "SpellBad", { fg = 'NONE', bg = 'NONE', sp = c.error, undercurl=true, })
  hl(0, "SpellCap", { fg = 'NONE', bg = 'NONE', sp = c.warning, undercurl=true, })
  hl(0, "SpellLocal", { fg = 'NONE', bg = 'NONE', sp = c.info, underline=true, })
  hl(0, "SpellRare", { fg = 'NONE', bg = 'NONE', sp = c.hint, underline=true, })
  hl(0, "WildMenu", { fg = 'NONE', bg = c.bg_visual })
  hl(0, "CursorLineNr", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "Comment", { fg = c.comment, bg = 'NONE', italic=true, })
  hl(0, "Folded", { fg = c.blue, bg = c.fg_gutter })
  hl(0, "FoldColumn", { fg = c.comment, bg = c.bg })
  hl(0, "LineNr", { fg = c.comment, bg = 'NONE' })
  hl(0, "LineNrAbove", { link = 'LineNr' })
  hl(0, "LineNrBelow", { link = 'LineNr' })
  hl(0, "FloatBorder", { fg = c.border_highlight, bg = c.bg_float })
  hl(0, "FloatTitle", { fg = c.border_highlight, bg = c.bg_float })
  hl(0, "Whitespace", { fg = c.fg_gutter, bg = 'NONE' })
  hl(0, "VertSplit", { fg = c.border, bg = 'NONE' })
  hl(0, "WinSeparator", { fg = c.border, bg = 'NONE', bold=true, })
  hl(0, "WinBar", { link = 'StatusLine' })
  hl(0, "WinBarNC", { link = 'StatusLineNC' })
  hl(0, "CursorLine", { fg = 'NONE', bg = c.bg_highlight })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.bg_highlight })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.black })
  hl(0, "Visual", { fg = 'NONE', bg = c.bg_visual })
  hl(0, "VisualNOS", { fg = 'NONE', bg = c.bg_visual })
  hl(0, "WarningMsg", { fg = c.warning, bg = 'NONE' })
  hl(0, "DiffAdd", { fg = 'NONE', bg = c.diff_add })
  hl(0, "DiffChange", { fg = 'NONE', bg = c.diff_change })
  hl(0, "DiffDelete", { fg = 'NONE', bg = c.diff_delete })
  hl(0, "DiffText", { fg = 'NONE', bg = c.diff_text })
  hl(0, "QuickFixLine", { fg = 'NONE', bg = c.bg_visual, bold=true, })
  hl(0, "Pmenu", { fg = c.fg, bg = c.bg_popup })
  hl(0, "PmenuMatch", { fg = c.blue1, bg = c.bg_popup })
  hl(0, "PmenuSel", { fg = 'NONE', bg = c.pmenu_sel_bg })
  hl(0, "PmenuMatchSel", { fg = c.blue1, bg = c.pmenu_sel_bg })
  hl(0, "PmenuSbar", { fg = 'NONE', bg = '#1F2335' })
  hl(0, "PmenuThumb", { fg = 'NONE', bg = c.fg_gutter })
  hl(0, "MatchWord", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParen", { fg = c.orange, bg = 'NONE', bold=true, })
  hl(0, "MatchWordCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParenCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Cursor", { fg = c.bg, bg = c.fg })
  hl(0, "lCursor", { fg = c.bg, bg = c.fg })
  hl(0, "CursorIM", { fg = c.bg, bg = c.fg })
  hl(0, "TermCursor", { fg = c.bg, bg = c.fg })
  hl(0, "TermCursorNC", { fg = c.bg, bg = c.fg })
  hl(0, "Conceal", { fg = c.dark5, bg = 'NONE' })
  hl(0, "Directory", { fg = c.yellow, bg = 'NONE' })
  hl(0, "SpecialKey", { fg = c.dark3, bg = 'NONE' })
  hl(0, "Title", { fg = c.blue, bg = 'NONE', bold=true, })
  hl(0, "ErrorMsg", { fg = c.error, bg = 'NONE' })
  hl(0, "Search", { fg = c.fg, bg = c.bg_search })
  hl(0, "IncSearch", { fg = c.black, bg = c.orange })
  hl(0, "CurSearch", { link = 'IncSearch' })
  hl(0, "Substitute", { fg = c.black, bg = c.red })
  hl(0, "MoreMsg", { fg = c.blue, bg = 'NONE' })
  hl(0, "Question", { fg = c.blue, bg = 'NONE' })
  hl(0, "EndOfBuffer", { fg = c.bg, bg = 'NONE' })
  hl(0, "NonText", { fg = c.dark3, bg = 'NONE' })
  hl(0, "Variable", { fg = c.fg, bg = 'NONE' })
  hl(0, "String", { fg = c.green, bg = 'NONE' })
  hl(0, "Character", { fg = c.green, bg = 'NONE' })
  hl(0, "Constant", { fg = c.white, bg = 'NONE' })
  hl(0, "Number", { link = 'Constant' })
  hl(0, "Boolean", { link = 'Constant' })
  hl(0, "Float", { link = 'Number' })
  hl(0, "Identifier", { fg = c.white, bg = 'NONE' })
  hl(0, "Function", { fg = c.blue, bg = 'NONE' })
  hl(0, "Operator", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Type", { fg = c.yellow, bg = 'NONE' })
  hl(0, "StorageClass", { fg = c.purple, bg = 'NONE' })
  hl(0, "Structure", { link = 'Type' })
  hl(0, "Typedef", { fg = c.blue, bg = 'NONE' })
  hl(0, "Keyword", { fg = c.purple, bg = 'NONE', italic=true, })
  hl(0, "Statement", { fg = c.magenta, bg = 'NONE' })
  hl(0, "Conditional", { fg = c.blue, bg = 'NONE' })
  hl(0, "Repeat", { fg = c.purple, bg = 'NONE' })
  hl(0, "Label", { fg = c.purple, bg = 'NONE' })
  hl(0, "Exception", { fg = c.purple, bg = 'NONE' })
  hl(0, "Include", { fg = c.purple, bg = 'NONE' })
  hl(0, "PreProc", { fg = c.orange3, bg = 'NONE' })
  hl(0, "Define", { link = 'PreProc' })
  hl(0, "Macro", { link = 'PreProc' })
  hl(0, "PreCondit", { link = 'PreProc' })
  hl(0, "Special", { fg = c.cyan, bg = 'NONE' })
  hl(0, "SpecialChar", { fg = c.white, bg = 'NONE' })
  hl(0, "Tag", { fg = c.blue, bg = 'NONE' })
  hl(0, "Debug", { fg = c.orange, bg = 'NONE' })
  hl(0, "Delimiter", { link = 'Special' })
  hl(0, "SpecialComment", { link = 'Special' })
  hl(0, "Underlined", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Bold", { fg = c.fg, bg = 'NONE', bold=true, })
  hl(0, "Italic", { fg = c.fg, bg = 'NONE', italic=true, })
  hl(0, "Ignore", { fg = c.cyan, bg = c.bg, bold=true, })
  hl(0, "Todo", { fg = c.bg, bg = c.yellow })
  hl(0, "Error", { fg = c.error, bg = 'NONE' })
  hl(0, "debugBreakpoint", { fg = c.info, bg = c.breakpoint_bg })
  hl(0, "debugPC", { fg = 'NONE', bg = c.bg_sidebar })
  hl(0, "TabLine", { fg = c.fg_gutter, bg = c.bg_statusline })
  hl(0, "TabLineSel", { fg = c.black, bg = c.blue })
  hl(0, "TabLineFill", { fg = 'NONE', bg = c.black })
  hl(0, "dosIniLabel", { link = 'TSProperty' })
  hl(0, "helpCommand", { fg = c.blue, bg = c.terminal_black })
  hl(0, "htmlH1", { fg = c.magenta, bg = 'NONE', bold=true, })
  hl(0, "htmlH2", { fg = c.blue, bg = 'NONE', bold=true, })
  hl(0, "qfFileName", { fg = c.blue, bg = 'NONE' })
  hl(0, "qfLineNr", { fg = c.dark5, bg = 'NONE' })
  hl(0, "ComplHint", { fg = c.terminal_black, bg = 'NONE' })
  hl(0, "healthError", { link = 'Error' })
  hl(0, "healthSuccess", { fg = c.green1, bg = 'NONE' })
  hl(0, "healthWarning", { fg = c.warning, bg = 'NONE' })
  hl(0, "diffAdded", { fg = c.git_add, bg = c.diff_add })
  hl(0, "diffRemoved", { fg = c.git_delete, bg = c.diff_delete })
  hl(0, "diffChanged", { fg = c.git_change, bg = c.diff_change })
  hl(0, "diffOldFile", { fg = c.blue1, bg = c.diff_delete })
  hl(0, "diffNewFile", { fg = c.blue1, bg = c.diff_add })
  hl(0, "diffFile", { fg = c.blue, bg = 'NONE' })
  hl(0, "diffLine", { fg = c.comment, bg = 'NONE' })
  hl(0, "diffIndexLine", { fg = c.magenta, bg = 'NONE' })
  hl(0, "helpExample", { fg = c.comment, bg = 'NONE' })

  -- Git
  hl(0, "SignAdd", { fg = c.git_add, bg = 'NONE' })
  hl(0, "SignChange", { fg = c.git_change, bg = 'NONE' })
  hl(0, "SignDelete", { fg = c.git_delete, bg = 'NONE' })
  hl(0, "GitSignsAdd", { fg = c.git_add, bg = 'NONE' })
  hl(0, "GitSignsChange", { fg = c.git_change, bg = 'NONE' })
  hl(0, "GitSignsDelete", { fg = c.git_delete, bg = 'NONE' })

  -- Treesitter
  hl(0, "TSComment", { link = 'Comment' })
  hl(0, "TSAnnotation", { link = 'PreProc' })
  hl(0, "TSAttribute", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSConstructor", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSType", { link = 'Type' })
  hl(0, "TSTypeBuiltin", { fg = c.red, bg = 'NONE' })
  hl(0, "TSConditional", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSException", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSInclude", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSKeywordReturn", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSKeyword", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSKeywordFunction", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSLabel", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSNamespace", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSRepeat", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSConstant", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSConstBuiltin", { fg = c.red, bg = 'NONE' })
  hl(0, "TSFloat", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSNumber", { link = 'Number' })
  hl(0, "TSBoolean", { link = 'Boolean' })
  hl(0, "TSCharacter", { fg = c.green, bg = 'NONE' })
  hl(0, "TSError", { link = 'Error' })
  hl(0, "TSFunction", { fg = c.blue, bg = 'NONE' })
  hl(0, "TSFuncBuiltin", { fg = c.blue, bg = 'NONE' })
  hl(0, "TSMethod", { fg = c.blue, bg = 'NONE' })
  hl(0, "@function.macro", { link = 'Macro' })
  hl(0, "TSVariable", { link = 'Variable' })
  hl(0, "TSVariableBuiltin", { fg = c.red, bg = 'NONE' })
  hl(0, "TSVariableMember", { fg = c.green, bg = 'NONE' })
  hl(0, "TSVariableParameter", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSVariableParameterBuiltin", { fg = '#D3A66A', bg = 'NONE' })
  hl(0, "TSProperty", { link = 'Identifier' })
  hl(0, "TSField", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSParameter", { fg = c.red, bg = 'NONE' })
  hl(0, "TSParameterReference", { fg = c.red, bg = 'NONE' })
  hl(0, "TSSymbol", { link = 'Identifier' })
  hl(0, "TSText", { link = 'String' })
  hl(0, "TSOperator", { link = 'Operator' })
  hl(0, "TSPunctDelimiter", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSPunctBracket", { fg = c.fg_dark, bg = 'NONE' })
  hl(0, "TSPunctSpecial", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSPunctSpecialMarkdown", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSString", { fg = c.green, bg = 'NONE' })
  hl(0, "TSStringDocument", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSStringRegex", { fg = c.blue6, bg = 'NONE' })
  hl(0, "TSStringEscape", { fg = c.magenta, bg = 'NONE' })
  hl(0, "TSTag", { link = 'TSLabel' })
  hl(0, "TSTagDelimiter", { link = 'Delimiter' })
  hl(0, "TSTagAttribute", { link = 'Macro' })
  hl(0, "TSEmphasis", { fg = 'NONE', bg = 'NONE', italic=true, })
  hl(0, "TSUnderline", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "TSTitle", { fg = c.fg, bg = 'NONE',  })
  hl(0, "TSLiteral", { link = 'Constant' })
  hl(0, "TSURI", { fg = c.orange, bg = 'NONE', underline=true, })
  hl(0, "TSKeywordOperator", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSStructure", { link = 'Type' })
  hl(0, "TSStrong", { fg = c.blue, bg = 'NONE', bold=true, })
  hl(0, "TSQueryLinterError", { fg = c.warning, bg = 'NONE' })
  hl(0, "TreesitterContext", { fg = 'NONE', bg = '#363C59' })

  -- markdown
  hl(0, "RenderMarkdownBullet", { fg = c.orange, bg = 'NONE' })
  hl(0, "RenderMarkdownCode", { fg = 'NONE', bg = c.bg_dark })
  hl(0, "RenderMarkdownDash", { fg = c.orange, bg = 'NONE' })
  hl(0, "RenderMarkdownTableHead", { fg = c.red, bg = 'NONE' })
  hl(0, "RenderMarkdownTableRow", { fg = c.orange, bg = 'NONE' })
  hl(0, "RenderMarkdownCodeInline", { link = '@markup.raw.markdown_inline' })

  -- Whichkey
  hl(0, "WhichKey", { fg = c.cyan, bg = 'NONE' })
  hl(0, "WhichKeyGroup", { fg = c.blue, bg = 'NONE' })
  hl(0, "WhichKeyDesc", { fg = c.magenta, bg = 'NONE' })
  hl(0, "WhichKeySeperator", { fg = c.comment, bg = 'NONE' })
  hl(0, "WhichKeyNormal", { fg = c.bg_sidebar, bg = 'NONE' })
  hl(0, "WhichKeyValue", { fg = c.dark5, bg = 'NONE' })

  -- LSP
  hl(0, "DiagnosticError", { fg = c.error, bg = 'NONE' })
  hl(0, "DiagnosticWarn", { fg = c.warning, bg = 'NONE' })
  hl(0, "DiagnosticInfo", { fg = c.info, bg = 'NONE' })
  hl(0, "DiagnosticHint", { fg = c.hint, bg = 'NONE' })
  hl(0, "DiagnosticUnnecessary", { fg = c.terminal_black, bg = 'NONE' })
  hl(0, "DiagnosticVirtualTextError", { fg = c.error, bg = '#37283D' })
  hl(0, "DiagnosticVirtualTextWarn", { fg = c.warning, bg = '#37333D' })
  hl(0, "DiagnosticVirtualTextInfo", { fg = c.info, bg = '#2E343C' })
  hl(0, "DiagnosticVirtualTextHint", { fg = c.hint, bg = '#203241' })
  hl(0, "DiagnosticUnderlineError", { fg = 'NONE', bg = 'NONE', sp = c.error, undercurl=true, })
  hl(0, "DiagnosticUnderlineWarn", { fg = 'NONE', bg = 'NONE', sp = c.warning, undercurl=true, })
  hl(0, "DiagnosticUnderlineInfo", { fg = 'NONE', bg = 'NONE', sp = c.info, undercurl=true, })
  hl(0, "DiagnosticUnderlineHint", { fg = 'NONE', bg = 'NONE', sp = c.hint, undercurl=true, })
  hl(0, "LspReferenceRead", { fg = 'NONE', bg = c.fg_gutter })
  hl(0, "LspReferenceText", { fg = 'NONE', bg = c.fg_gutter })
  hl(0, "LspReferenceWrite", { fg = 'NONE', bg = c.fg_gutter })
  hl(0, "LspCodeLens", { fg = c.comment, bg = 'NONE' })
  hl(0, "LspInlayHint", { fg = c.dark3, bg = '#23273D' })
  hl(0, "LspInfoBorder", { fg = c.border_highlight, bg = c.bg_float })
  hl(0, "LspSignatureActiveParameter", { fg = 'NONE', bg = '#252C48', bold=true, })

  -- SemanticTokens
  hl(0, "@lsp.mod.mutable", { fg = c.blue3, bg = 'NONE', underline=true, })
  hl(0, "@lsp.type.property", { link = 'TSProperty' })
  hl(0, "@lsp.type.builtinType", { link = 'TSTypeBuiltin' })
  hl(0, "@lsp.type.interface", { fg = c.purple2, bg = 'NONE', bold=true, })
  hl(0, "@lsp.type.macro", { link = 'Macro' })
  hl(0, "@lsp.mod.unsafe", { link = 'Error' })

  -- Telescope
  hl(0, "TelescopeBorder", { fg = c.border_highlight, bg = c.bg_float })
  hl(0, "TelescopeNormal", { fg = c.fg, bg = c.bg_float })
  hl(0, "TelescopePromptBorder", { fg = c.orange, bg = c.bg_float })
  hl(0, "TelescopePromptTitle", { fg = c.orange, bg = c.bg_float })
  hl(0, "TelescopeResultsComment", { fg = c.dark3, bg = 'NONE' })

  -- StatusLine
  hl(0, "StatusLine", { fg = c.fg_sidebar, bg = c.bg_statusline })
  hl(0, "StatusLineNC", { fg = c.fg_gutter, bg = c.bg_statusline })

  -- Blink
  hl(0, "BlinkCmpDoc", { fg = c.fg, bg = c.bg_float })
  hl(0, "BlinkCmpDocBorder", { fg = c.border_highlight, bg = c.bg_float })
  hl(0, "BlinkCmpGhostText", { fg = c.terminal_black, bg = 'NONE' })
  hl(0, "BlinkCmpKindCodeium", { fg = c.teal, bg = 'NONE' })
  hl(0, "BlinkCmpKindCopilot", { fg = c.teal, bg = 'NONE' })
  hl(0, "BlinkCmpKindDefault", { fg = c.fg_dark, bg = 'NONE' })
  hl(0, "BlinkCmpKindSupermaven", { fg = c.teal, bg = 'NONE' })
  hl(0, "BlinkCmpKindTabNine", { fg = c.teal, bg = 'NONE' })
  hl(0, "BlinkCmpLabel", { fg = c.fg, bg = 'NONE' })
  hl(0, "BlinkCmpLabelDeprecated", { fg = c.fg_gutter, bg = 'NONE', strikethrough=true, })
  hl(0, "BlinkCmpLabelMatch", { fg = c.blue1, bg = 'NONE' })
  hl(0, "BlinkCmpMenu", { fg = c.fg, bg = c.bg_float })
  hl(0, "BlinkCmpMenuBorder", { fg = c.border_highlight, bg = c.bg_float })
  hl(0, "BlinkCmpSignatureHelp", { fg = c.fg, bg = c.bg_float })
  hl(0, "BlinkCmpSignatureHelpBorder", { fg = c.border_highlight, bg = c.bg_float })
end

return theme