[information]
name = "moonlight"
background = "dark"
author = "ZXY595 <zxy_595@qq.com>"

[palette]
bg = "#212337"
bg_dark = "#1f2335"
bg_dark1 = "#1b1e2d"
bg_highlight = "#292e42"
blue = "#7aa2f7"
blue0 = "#3d59a1"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue3 = "#60BDFF"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
comment = "#7486d6"
cyan = "#78DBFF"
dark3 = "#545c7e"
dark5 = "#737aa2"
fg = "#e4f3fa"
fg_dark = "#a9b1d6"
fg_gutter = "#3b4261"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
green3 = "#ABEBC6"
magenta = "#bb9af7"
magenta2 = "#ff007c"
orange = "#f67f81"
orange2 = "#DEA584"
orange3 = "#ff9900"
purple = "#b4a4f4"
purple2 = "#99A4FD"
red = "#ff757f"
red1 = "#FF5370"
teal = "#1abc9c"
terminal_black = "#414868"
yellow = "#FFC777"
pink = "#FCA7EA"
white = "#C8D3F5"

black = "#1A1C2C"
fg_sidebar = "#a9b1d6"  # fg_dark
bg_sidebar = "#1f2335"  # bg_dark
fg_float = "#e4f3fa"  # fg
bg_float = "#1f2335"  # bg_dark

bg_visual = "#2C3961"
bg_search = "#3d59a1"  # blue0

border = "#2ac3de"  # blue1

error = "#FF5370"  # red1
todo = "#7aa2f7"  # blue
warning = "#FFC777"  # yellow
info = "#9ece6a" # green
hint = "#b4a4f4" # purple

breakpoint_bg = "#2E343C"

bg_popup = "#1f2335"  # bg_dark
bg_statusline = "#1f2335"  # bg_dark
pmenu_sel_bg = "#363C59"

diff_add = "#294457"
diff_delete = "#592F45"
diff_change = "#272D45"
diff_text = "#394b70"  # blue7

git_add = "#449dab"
git_change = "#6183bb"
git_delete = "#914c54"

# The format is "foreground background style special blend"
# The - is used to skip a particular section and replace it with NONE
# You can also choose to link a highlight group to another by passing link:<name of hl group>
#
# Style Options:
#
#     o: standout
#     u: underline
#     c: undercurl
#     d: underdouble
#     t: underdotted
#     h: underdashed
#     s: strikethrough
#     i: italic
#     b: bold
#     r: reverse
#     n: nocombine
[highlights]
Normal = "fg bg"
NormalNC = "fg bg"
NormalSB = "fg_sidebar bg_sidebar"
NormalFloat = "fg_float bg_float"
SignColumn = "fg_gutter bg"
SignColumnSB = "fg_gutter bg_sidebar"
MsgArea = "fg_dark"
ModeMsg = "fg_dark - b"
MsgSeparator = "fg bg"
SpellBad = "- - c error"
SpellCap = "- - c warning"
SpellLocal = "- - u info"
SpellRare = "- - u hint"
WildMenu = "- bg_visual"
CursorLineNr = "pink - b"
Comment = "comment - i"
Folded = "blue fg_gutter"
FoldColumn = "comment bg"
LineNr = "comment"
LineNrAbove = "link:LineNr"
LineNrBelow = "link:LineNr"
FloatBorder = "border bg_float"
FloatTitle = "border bg_float"
Whitespace = "fg_gutter"
VertSplit = "border"
WinSeparator = "border - b"
WinBar = "link:StatusLine"
WinBarNC = "link:StatusLineNC"
CursorLine = "- bg_highlight"
CursorColumn = "- bg_highlight"
ColorColumn = "- black"
Visual = "- bg_visual"
VisualNOS = "- bg_visual"
WarningMsg = "warning"
DiffAdd = "- diff_add"
DiffChange = "- diff_change"
DiffDelete = "- diff_delete"
DiffText = "- diff_text"
QuickFixLine = "- bg_visual b"
Pmenu = "fg bg_popup"
PmenuMatch = "blue1 bg_popup"
PmenuSel = "- pmenu_sel_bg"
PmenuMatchSel = "blue1 pmenu_sel_bg"
PmenuSbar = "- #1F2335"
PmenuThumb = "- fg_gutter"
MatchWord = "- - u"
MatchParen = "orange - b"
MatchWordCur = "- - u"
MatchParenCur = "- - u"
Cursor = "bg fg"
lCursor = "bg fg"
CursorIM = "bg fg"
TermCursor = "bg fg"
TermCursorNC = "bg fg"
Conceal = "dark5"
Directory = "yellow"
SpecialKey = "dark3 -"
Title = "blue - b"
ErrorMsg = "error"
Search = "fg bg_search"
IncSearch = "black orange"
CurSearch = "link:IncSearch"
Substitute = "black red"
MoreMsg = "blue"
Question = "blue"
EndOfBuffer = "bg"
NonText = "dark3"
Variable = "fg"
String = "green"
Character = "green"
Constant = "white"
Number = "link:Constant"
Boolean = "link:Constant"
Float = "link:Number"
Identifier = "white"
Function = "blue"
Operator = "cyan"
Type = "yellow"
StorageClass = "purple"
Structure = "link:Type"
Typedef = "blue"
Keyword = "purple - i"
Statement = "magenta"
Conditional = "blue"
Repeat = "purple"
Label = "purple"
Exception = "purple"
Include = "purple"
PreProc = "orange3"
Define = "link:PreProc"
Macro = "link:PreProc"
PreCondit = "link:PreProc"
Special = "cyan"
SpecialChar = "white"
Tag = "blue"
Debug = "orange"
Delimiter = "link:Special"
SpecialComment = "link:Special"
Underlined = "- - u"
Bold = "fg - b"
Italic = "fg - i"
Ignore = "cyan bg b"
Todo = "bg yellow"
Error = "error"
debugBreakpoint = "info breakpoint_bg"
debugPC = "- bg_sidebar"
TabLine = "fg_gutter bg_statusline"
TabLineSel = "black blue"
TabLineFill = "- black"
dosIniLabel = "link:TSProperty"
helpCommand = "blue terminal_black"
htmlH1 = "magenta - b"
htmlH2 = "blue - b"
qfFileName = "blue"
qfLineNr = "dark5"
ComplHint = "terminal_black"
healthError = "link:Error"
healthSuccess = "green1"
healthWarning = "warning"
diffAdded = "git_add diff_add"
diffRemoved = "git_delete diff_delete"
diffChanged = "git_change diff_change"
diffOldFile = "blue1 diff_delete"
diffNewFile = "blue1 diff_add"
diffFile = "blue"
diffLine = "comment"
diffIndexLine = "magenta"
helpExample = "comment"

[Git]
SignAdd = "git_add"
SignChange = "git_change"
SignDelete = "git_delete"
GitSignsAdd = "git_add"
GitSignsChange = "git_change"
GitSignsDelete = "git_delete"

[Treesitter]
TSComment = "link:Comment"
TSAnnotation = "link:PreProc"
TSAttribute = "cyan"
TSConstructor = "cyan"
TSType = "link:Type"
TSTypeBuiltin = "red"
TSConditional = "yellow"
TSException = "purple"
TSInclude = "purple"
TSKeywordReturn = "purple"
TSKeyword = "purple"
TSKeywordFunction = "purple"
TSLabel = "purple"
TSNamespace = "cyan"
TSRepeat = "yellow"
TSConstant = "orange"
TSConstBuiltin = "red"
TSFloat = "orange"
TSNumber = "link:Number"
TSBoolean = "link:Boolean"
TSCharacter = "green"
TSError = "link:Error"
TSFunction = "blue"
TSFuncBuiltin = "blue"
TSMethod = "blue"
"@function.macro" = "link:Macro"
TSVariable = "link:Variable"
TSVariableBuiltin = "red"
TSVariableMember = "green"
TSVariableParameter = "pink"
TSVariableParameterBuiltin = "#D3A66A"
TSProperty = "link:Identifier"
TSField = "fg"
TSParameter = "red"
TSParameterReference = "red"
TSSymbol = "link:Identifier"
TSText = "link:String"
TSOperator = "link:Operator"
TSPunctDelimiter = "cyan"
TSPunctBracket = "fg_dark"
TSPunctSpecial = "cyan"
TSPunctSpecialMarkdown = "orange"
TSString = "green"
TSStringDocument = "yellow"
TSStringRegex = "blue6"
TSStringEscape = "magenta"
TSTag = "link:TSLabel"
TSTagDelimiter = "link:Delimiter"
TSTagAttribute = "link:Macro"
TSEmphasis = "- - i"
TSUnderline = "- - u"
TSTitle = "fg - -"
TSLiteral = "link:Constant"
TSURI = "orange - u"
TSKeywordOperator = "purple"
TSStructure = "link:Type"
TSStrong = "blue - b"
TSQueryLinterError = "warning"
TreesitterContext = "- #363C59"

[markdown]
RenderMarkdownBullet = "orange"
RenderMarkdownCode = "- bg_dark"
RenderMarkdownDash = "orange"
RenderMarkdownTableHead = "red"
RenderMarkdownTableRow = "orange"
RenderMarkdownCodeInline = "link:@markup.raw.markdown_inline"

[Whichkey]
WhichKey = "cyan"
WhichKeyGroup = "blue"
WhichKeyDesc = "magenta"
WhichKeySeperator = "comment"
WhichKeyNormal = "bg_sidebar"
WhichKeyValue = "dark5"

[LSP]
DiagnosticError = "error"
DiagnosticWarn = "warning"
DiagnosticInfo = "info"
DiagnosticHint = "hint"
DiagnosticUnnecessary = "terminal_black"
DiagnosticVirtualTextError = "error #37283D"
DiagnosticVirtualTextWarn = "warning #37333D"
DiagnosticVirtualTextInfo = "info #2E343C"
DiagnosticVirtualTextHint = "hint #203241"
DiagnosticUnderlineError = "- - c error"
DiagnosticUnderlineWarn = "- - c warning"
DiagnosticUnderlineInfo = "- - c info"
DiagnosticUnderlineHint = "- - c hint"
LspReferenceRead = "- fg_gutter"
LspReferenceText = "- fg_gutter"
LspReferenceWrite = "- fg_gutter"
LspCodeLens = "comment"
LspInlayHint = "dark3 #23273D"
LspInfoBorder = "border bg_float"
LspSignatureActiveParameter = "- #252C48 b"

[SemanticTokens]
"@lsp.mod.mutable" = "blue3 - u"
"@lsp.type.typeAlias" = "link:Type"
"@lsp.type.property" = "link:TSProperty"
"@lsp.type.builtinType" = "link:TSTypeBuiltin"
"@lsp.type.interface" = "pink - b"
"@lsp.type.macro" = "link:Macro"
"@lsp.mod.unsafe" = "link:Error"

[Telescope]
TelescopeBorder = "border bg_float"
TelescopeNormal = "fg bg_float"
TelescopePromptBorder = "orange bg_float"
TelescopePromptTitle = "orange bg_float"
TelescopeResultsComment = "dark3"

[StatusLine]
StatusLine = "fg_sidebar bg_statusline"
StatusLineNC = "fg_gutter bg_statusline"

[Blink]
BlinkCmpDoc = "fg bg_float"
BlinkCmpDocBorder = "border bg_float"
BlinkCmpGhostText = "terminal_black"
BlinkCmpKindCodeium = "teal"
BlinkCmpKindCopilot = "teal"
BlinkCmpKindDefault = "fg_dark"
BlinkCmpKindSupermaven = "teal"
BlinkCmpKindTabNine = "teal"
BlinkCmpLabel = "fg"
BlinkCmpLabelDeprecated = "fg_gutter - s"
BlinkCmpLabelMatch = "blue1"
BlinkCmpMenu = "fg bg_float"
BlinkCmpMenuBorder = "border bg_float"
BlinkCmpSignatureHelp = "fg bg_float"
BlinkCmpSignatureHelpBorder = "border bg_float"

# [Cmp]
# CmpDocumentation = "fg bg_float"
# CmpDocumentationBorder = "border bg_float"
# CmpGhostText = "terminal_black"
# CmpItemAbbr = "fg"
# CmpItemAbbrDeprecated = "fg_gutter - s"
# CmpItemAbbrMatch = "blue1"
# CmpItemAbbrMatchFuzzy = "blue1"
# CmpItemKindCodeium = "teal"
# CmpItemKindCopilot = "teal"
# CmpItemKindSupermaven = "teal"
# CmpItemKindDefault = "fg_dark"
# CmpItemKindTabNine = "teal"
# CmpItemMenu = "comment"

[Rainbow]
RainbowCyan = "cyan"
RainbowBlue = "blue3"
RainbowViolet = "purple"
RainbowRed = "red"
RainbowOrange = "orange"
RainbowYellow = "yellow"
RainbowGreen = "green"
